package com.schegolevalex.mm.mmparser.bot.page.base;

public enum Page {
    NEW_CONVERSATION,
    MAIN,
    SUGGESTION_TO_INPUT_LINK,
    INPUT_LINK,
    WATCH_PRODUCTS,
    WATCH_PROMOS,
    UNEXPECTED,
    ADD_PROMO_STEP_PRICE,
    ADD_PROMO_STEP_DISCOUNT,
    ADD_PROMO_STEP_SUCCESSFUL,
    DELETE_PRODUCT,
    APPLY_PROMO,
    PRODUCT_NOTIFICATIONS,
    COMMON_SETTINGS,
    PROMOS_SETTINGS,
    CASHBACK_SETTINGS,
    PRODUCT_SETTINGS,
    NOTIFICATIONS_SETTINGS,
    CONFIRM_DELETE_PROMO,
    DELETE_PROMO, CONFIRM_DELETE_PRODUCT, FILTERS_SETTINGS, WATCH_FILTERS, DELETE_FILTER, CONFIRM_DELETE_FILTER,
}