services:
  mm-parser-database:
    container_name: mm-parser-database
    image: postgres:16.3
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
#      POSTGRES_TIMEZONE: Europe/Moscow
#      TZ: Europe/Moscow
#      PGTZ: Europe/Moscow
    user: postgres

    volumes:
      - mm-parser-data:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 3

  redis:
    container_name: redis
    image: redis
    restart: on-failure
    ports:
      - "6379:6379"

volumes:
  mm-parser-data:

