server:
  port: 8080

spring:
  application:
    name: mm-parser
  web:
    locale: ru
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
#        jakarta.persistence.validation.mode: none

telegram-bot:
  botUsername: schegolev_test_bot
  creatorId: 50928456
  botToken: 6962805254:AAGP1UolXDpSR7cdMAik9LDQl72a1tnKghI

mm:
  baseUrl: https://megamarket.ru/
  rqueue:
    product-queue: product-queue
    notification-queue: notification-queue
  parser:
    max-attempts-to-open-url: 3
    free-parser-delay-in-minutes: 10
  parser-pool:
    min-idle: 1
    max-idle: 1
    wait-idle-in-seconds: 30

rqueue:
  reactive:
    enabled: false
  web:
    enable: false

logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#    org.hibernate.SQL: DEBUG
#    org.springframework.transaction: TRACE
#    org.springframework.orm.jpa.JpaTransactionManager: DEBUG
#    com.schegolevalex.mm.mmparser: TRACE