package com.schegolevalex.mm.mmparser.bot.state;

public enum BotState {
    NEW_STATE,
    MAIN_PAGE_ACTION,
    SUGGESTION_TO_INPUT_LINK,
    INPUT_LINK,
    WATCH_LINKS,
    SETTINGS,
    PROMOS_SETTINGS,
    CASHBACK_SETTINGS,
    UNEXPECTED,
    ADD_PROMO_STEP_PRICE,
    WATCH_PROMOS,
    ADD_PROMO_STEP_DISCOUNT,
    ADD_PROMO_STEP_SUCCESSFUL,
}